# Generated by Django 5.1.15 on 2026-07-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_lesson_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taught_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='catalog.subject'),
        ),
    ]
