# Generated by Django 5.1.15 on 2026-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_taught_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_channel',
            field=models.CharField(choices=[('email', 'بريد إلكتروني'), ('telegram', 'تيليجرام'), ('whatsapp', 'واتساب')], default='email', max_length=20, verbose_name='وسيلة التواصل'),
        ),
    ]
