# Generated by Django 5.1.15 on 2026-07-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegram_whatsapp_oauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_channel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.DeleteModel(
            name='WhatsAppAuthSession',
        ),
    ]
