# Generated by Django 5.1.15 on 2026-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_telegram_whatsapp_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='معرف تيليجرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='يوزر تيليجرام'),
        ),
    ]
