# Generated by Django 5.1.15 on 2026-07-31 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_telegram_oidc_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramoauthstate',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramoauthstate',
            name='consumed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_oauth_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
