# Generated by Django 5.1.15 on 2026-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_lessonsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
