# Generated by Django 5.1.15 on 2026-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'بطاقة بنكية'), ('vodafone_cash', 'فودافون كاش'), ('wallet', 'محفظة إلكترونية'), ('manual', 'تفعيل إداري')], max_length=15),
        ),
    ]
