# Generated by Django 5.1.15 on 2026-07-15 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text; may contain $LaTeX$ fragments')),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(help_text='Option key, e.g. أ', max_length=10)),
                ('video_bunny_id', models.CharField(blank=True, max_length=100)),
                ('video_timing', models.CharField(choices=[('before', 'قبل الإجابة'), ('after', 'بعد الإجابة')], default='after', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10)),
                ('written_correction', models.TextField(blank=True)),
                ('free_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.studygroup')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='catalog.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='catalog.subject')),
            ],
            options={
                'ordering': ['lesson', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('simulator', 'المحاكي الشخصي'), ('teacher', 'اختبار المدرس')], max_length=12)),
                ('difficulty_preset', models.CharField(blank=True, choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], max_length=10)),
                ('review_mode', models.CharField(choices=[('immediate', 'فورية'), ('final', 'نهائية')], default='final', max_length=10)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('is_free_attempt', models.BooleanField(default=False, help_text='Capped free-tier attempt (max 10 questions)')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('finished', 'منتهي'), ('auto_submitted', 'إرسال تلقائي')], default='in_progress', max_length=15)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='groups.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='catalog.subject')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text; may contain $LaTeX$ fragments')),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(help_text='Option key, e.g. أ', max_length=10)),
                ('video_bunny_id', models.CharField(blank=True, max_length=100)),
                ('video_timing', models.CharField(choices=[('before', 'قبل الإجابة'), ('after', 'بعد الإجابة')], default='after', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='groups.studygroup')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='catalog.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='catalog.subject')),
            ],
            options={
                'ordering': ['lesson', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('selected_answer', models.CharField(blank=True, max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.collectionquestion')),
            ],
            options={
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ExamLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='assessments.exam')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lesson')),
            ],
            options={
                'unique_together': {('exam', 'lesson')},
            },
        ),
    ]
