# Generated by Django 5.1.15 on 2026-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_collectionquestion_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10),
        ),
    ]
