# Generated by Django 5.1.15 on 2026-08-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_homeworkquestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collectionquestion',
            name='explanation_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collectionquestion',
            name='text_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='explanation_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='text_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
