# Generated by Django 5.1.15 on 2026-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_homework_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionquestion',
            name='question_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
