# Generated by Django 5.1.15 on 2026-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_collection_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionquestion',
            name='video_bunny_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='video_bunny_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
