# Generated by Django 5.1.15 on 2026-08-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, default='', help_text='اسم اختياري للحصة (مثال: مراجعة الباب الأول)', max_length=200),
        ),
    ]
