# Generated by Django 5.1.15 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='bunny_video_id',
            field=models.CharField(max_length=500),
        ),
    ]
